function scenes = extra_path_scenes(params)
%EXTRA_PATH_SCENES 返回额外路径规划测试/可视化场景
%
%   scenes = extra_path_scenes(params)
%
%   这些场景用于观察 SR3 在不同障碍布局下的路径规划与绕障效果。

    n = params.n;
    z = zeros(1, n);

    scenes(1) = make_scene( ...
        'baseline_no_obstacle', ...
        z, ...
        [pi/3, -pi/6, pi/8, pi/5, pi/6, -pi/4], ...
        zeros(0, 4), ...
        3.0, 0.02);

    scenes(end+1) = make_scene( ...
        'single_sphere_high_workspace', ...
        z, ...
        [pi/2, -pi/6, pi/6, 0, pi/6, 0], ...
        [-80, -80, 1010, 80], ...
        3.0, 0.02);

    scenes(end+1) = make_scene( ...
        'single_sphere_sweep_center', ...
        [-pi/2, -pi/6, 0, 0, pi/3, 0], ...
        [ pi/2, -pi/6, 0, 0, pi/3, 0], ...
        [-120, 0, 868, 80], ...
        4.0, 0.02);

    scenes(end+1) = make_scene( ...
        'single_sphere_diagonal_motion', ...
        [0, -pi/4, pi/4, 0, pi/6, 0], ...
        [pi/2, -pi/5, -pi/5, pi/4, pi/3, -pi/3], ...
        [-235, -143, 864, 80], ...
        4.0, 0.02);

    scenes(end+1) = make_scene( ...
        'three_spheres_sweep', ...
        [-pi/2, -pi/6, 0, 0, pi/3, 0], ...
        [ pi/2, -pi/6, 0, 0, pi/3, 0], ...
        [ -85,  85, 868, 65;
          -120,   0, 868, 65;
           -85, -85, 868, 65], ...
        4.0, 0.02);
end

function scene = make_scene(name, q_start, q_goal, obstacles, T_total, dt)
    scene.name = name;
    scene.q_start = q_start;
    scene.q_goal = q_goal;
    scene.obstacles = obstacles;
    scene.T_total = T_total;
    scene.dt = dt;
end
